### PR TITLE
chore: migrate to Trampoline V2

### PR DESCRIPTION
**Pull request by tmatsuo**
It will allow you to run the builds locally. For example, here is the
command for running the presubmit system test:

```sh
TRAMPOLINE_IMAGE=gcr.io/cloud-devrel-kokoro-resources/node:12-user \
    TRAMPOLINE_BUILD_FILE=.kokoro/system-test.sh \
    SECRET_MANAGER_KEYS="npm_publish_token" \
    .kokoro/trampoline_v2.sh
```

Note: the current presubmit system test(.kokoro/presubmit/node12/system-test.cfg)
doesn't utilize any secrets.

### CODE REVIEW

**Comment by tmatsuo** [comment]
@bcoe Do you know what is `Summary Check for ci/kokoro: Samples test`? It seems it's a required check.

**Comment by bcoe** [comment]
@tmatsuo, @sofisl has been working on an experiment with GitHub actions that would allow us to make Sample/System tests optional for some types of PRs. Phishing Protection happened to be where we're testing this too.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
this is looking good, I'd like to generate it from your open PR on syntool though before merging 😄

**Comment by bcoe** [comment]
closing in favor of:

https://github.com/googleapis/nodejs-phishing-protection/pull/202

**Pull request closed without merging**
